### ISSUE TITLE
SDB plug in load error sometimes

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#151]
![preview-chat-2021-05-07_13 31 47](https://user-images.githubusercontent.com/11965250/117407596-59d81300-af41-11eb-8639-aa4dd93c9cfa.jpg)

I've had this error once, yesterday.  I think it was when  went from Nightly to Beta, inside the app.  I fixed it by doing a "reset settings" in the cloud updater. I had assumed I'd caused the problem with my manual-file copying.

However, the pic above is from a non-technical user today, so there must be a way to cause this error in normal use.

There's no way to use the app when this happens. The next page, the app is nonworking.

**Comment by ebengoechea** [comment]
Yes, this is a known issue that happens because 
1) plugins are not reverted when you downgrade the app (in this case it should be removed as it was not available in previous beta); and
2) plugin code is always sourced, even if disabled.

The old versions of SDB, DGUI and DSx DYE are not compatible with the new DUI code (as they did similar extensions to the GUI code but in slightly different ways), and that is triggering the error.

I think that to prevent this type of problems in the future both issues above must be addressed. The second problem could be solved using a safe interpreter to source, as you have suggested some time. For the first problem I’m not sure. I think @Mimoja and @jeffsf have thought about it but don’t know if something has been done.

In the short run, you have to manually remove plugin folders that were not there in the beta/stable branch and were added in nightly, in this case SDB.

**Comment by ebengoechea** [comment]
> However, the pic above is from a non-technical user today, so there must be a way to cause this error in normal use.

The only way this can be triggered is by installing nightly and then downgrading to beta or stable. A "normal" user shouldn't be doing that. Maybe it would be wise to hide the "nightly" option on the app behind a setting that must be manually enabled in settings.tdb?

**Comment by decentjohn** [comment]
It's a pretty rare case right now, so I think my preference is to fix it correctly now, and then push out a new beta.

re: @Mimoja "plugin code is always sourced, even if disabled." -

 if we source into an child interpreter, we can delete each interpreter as each plugin is sourced, and thus also ignore any plugin that has an error.  Simply skip listing it, or put "not available" on its description"

**Comment by Mimoja** [comment]
@decentjohn no longer the case sind 1.34.20

**Comment by decentjohn** [comment]
Ok great, so we just need to have a beta download with the fix to make this go away.

**Comment by Mimoja** [comment]
@decentjohn yes.
