### ISSUE TITLE
reformat all Tcl cde

### ISSUE THREAD

**Issue by decentjohn** [decentespresso/de1app#9]
@nicpottier wrote:
https://github.com/decentespresso/de1app/issues/6

"Though I love it and again, not sure on TCL feasibility, but auto-formatting can be a nice thing to have once there are new people committing. Won't bite that off yet though."

There are a few source code formatters out there, which you can find on the tcl wiki, such as
https://wiki.tcl-lang.org/page/frink
https://wiki.tcl-lang.org/page/Reformatting+Tcl+code+indentation

but I'm unsure about this.  

The main "war" with code formatting in C/C++ is brackets, and with Tcl there is a style enforced.

We could require 4-space tab formatting.

Otherwise, though, I think that "easy to read and verify" is the most important thing, and needs a human to assess that.

**Comment by barneyhawes** [comment]
When I was learning Tcl and the Decent codebase, it took me longer than it should have done to work out what was a string because strings are often not quoted. I have been much more generous in my use of quotes in my own code. There may be reasons why this is a good or bad idea that I am unaware of, or indeed standards for use of quotes in Tcl.

**Comment by decentjohn** [comment]
I agree Barney, it's better to always "quote" or {quote} strings in Tcl code, to make it more legible.  

Writing
if {$x == TRUE} ...

is confusing.
